import Layout from "/components/layout/Layout";
import "./globals.css"

export const metadata = {
  title: "car-project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Layout>{children}</Layout>
      </body>
    </html>
  );
}
